### ISSUE TITLE
Add longer description/citation to readme

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.fourigui#17]
if relevant for citation

**Comment by sbillinge** [comment]
yes, there is a publshed paper that needs to be referenced:
https://doi.org/10.1107/S2052252522006674

**Comment by sbillinge** [comment]
also we want a longer description!  Please harvest from the paper and any description in the regolith database.

**Comment by bobleesj** [comment]
yes, will try to write a longer description and make a PR for discussion

**Comment by bobleesj** [comment]
@cadenmyers13 Hi Caden, would you be able to help write a longer description and add the citation (using the diffpy.structure citation format) based on the publication above in the readme? We are planning on making a full-release next week. Many tasks are updated in `operation-release-everything` Week 5.

**Comment by cadenmyers13** [comment]
> @cadenmyers13 Hi Caden, would you be able to help write a longer description and add the citation (using the diffpy.structure citation format) based on the publication above in the readme? We are planning on making a full-release next week. Many tasks are updated in `operation-release-everything` Week 5.

done

**Comment by bobleesj** [comment]
Thanks @cadenmyers13

**Comment by bobleesj** [comment]
Closed by #21
