### ISSUE TITLE
Fix CI failing

### ISSUE THREAD

**Issue by Filippo1598** [diffpy/diffpy.fourigui#26]
![image](https://github.com/user-attachments/assets/c9f30ce0-c22a-468f-8554-ac061d4af364)

**Comment by bobleesj** [comment]
Closed!

<img width="647" alt="Screenshot 2024-10-09 at 5 02 53 PM" src="https://github.com/user-attachments/assets/c83c4ac8-360c-4586-a9bc-0a71712036cc">

**Comment by bobleesj** [comment]
@Filippo1598 Please close the issue.
