### ISSUE TITLE
Ready for v0.1.1 PyPI/GitHub release

### ISSUE THREAD

**Issue by cadenmyers13** [diffpy/diffpy.fourigui#31]
### Release checklist for GitHub contributors

- [x] All PRs/issues attached to the release are merged.
- [x] All the badges on the README are passing. (assigned to @bobleesj) 
- [x] License information is verified as correct. If you are unsure, please comment below.
- [x] Locally rendered documentation contains all appropriate pages, including API references (check no modules are
  missing), tutorials (no tutorial in `diffpy.fourigui`, and other human-written text is up-to-date with any changes in the code.
- [x] Installation instructions in the README, documentation and on the website (**_this should be handled after release_**) (e.g., diffpy.org) are updated and tested
- [x] Successfully run any tutorial examples or do functional testing in some other way.  #40 
- [ ] links on README are working #33 
- [x] Grammar and writing quality have been checked (no typos).

Please mention @sbillinge when you are ready for release. Include any additional comments necessary, such as
version information and details about the pre-release.

**Comment by sbillinge** [comment]
Thanks @cadenmyers13 please ping me again when all the items are completed.

**Comment by cadenmyers13** [comment]
@bobleesj Following the README, when I install with `conda install diffpy.fourigui` I get the installation error that `diffpy.fourigui` is not available on conda-forge. However, it install with `pip install diffpy.fourigui`. Is this because this package isn't on `conda-forge`?

**Comment by bobleesj** [comment]
@cadenmyers13 for conda-forge, yes. We currently have it under the `rc`pre-release channel.

**Comment by sbillinge** [comment]
@cadenmyers13 I changed this to `0.1.1` in the title.  This is the checklist for the next release so we want to bump the number.  We will do a pre-release (so there wil be an rc0) but it will be `0.1.1rc0` but I don't think we need a separate checklist for the rc's

**Comment by sbillinge** [comment]
@cadenmyers13 I added issues that we want to close on this release to the 0.1.1 release milestone.

**Comment by bobleesj** [comment]
@sbillinge 

Could you please setup codecov token for `diffpy.fourigui`? Appears diffpy.fourigui has not been configured as expected: https://app.codecov.io/gh/diffpy

<img width="657" alt="Screenshot 2024-10-23 at 8 12 52 PM" src="https://github.com/user-attachments/assets/27fc6d1d-b307-4402-a0bd-557bc89cfbe3">

**Comment by sbillinge** [comment]
OK, not sure how to do this.  I thought I configured it correctly and added the `CODECOV_TOKEN` to the repo, but for some reason the upload to codecov step is being skipped in the `CI` workflow, and no coverage is uploaded.

**Comment by cadenmyers13** [comment]
@sbillinge Can I get a verification that the licensing is correct for this package?

**Comment by sbillinge** [comment]
> @sbillinge Can I get a verification that the licensing is correct for this package?

yes, can confirm.   I checked that on the list.

**Comment by cadenmyers13** [comment]
@sbillinge @bobleesj Once the opened PRs are confirmed and merged we should be good to release

**Comment by sbillinge** [comment]
> @sbillinge @bobleesj Once the opened PRs are confirmed and merged we should be good to release

in other words, we are not ready for release.   Please let me know when we are.....

**Comment by cadenmyers13** [comment]
closing for updated checklist

**Comment by bobleesj** [comment]
@cadenmyers13 Please provide a bit more context on why this issue is closed while we have a checklist for 0.2.0 being created. https://github.com/diffpy/diffpy.fourigui/issues/65#issuecomment-2468566818

I recall 0.1.1 was simply for recutting and 0.2.0 would be recutting + supporting py 3.13

**Comment by cadenmyers13** [comment]
> @cadenmyers13 Please provide a bit more context on why this issue is closed while we have a checklist for 0.2.0 being created. [#65 (comment)](https://github.com/diffpy/diffpy.fourigui/issues/65#issuecomment-2468566818)
> 
> I recall 0.1.1 was simply for recutting and 0.2.0 would be recutting + supporting py 3.13

comment has been updated^

**Comment by sbillinge** [comment]
Closed as completed.
