### ISSUE TITLE
Qmin Qmax to be within mask range

### ISSUE THREAD

**Issue by cadenmyers13** [diffpy/diffpy.fourigui#61]

**Comment by bobleesj** [comment]
@cadenmyers13 once this issue is resolved, are we ready for py 313 release?

**Comment by cadenmyers13** [comment]
> @cadenmyers13 once this issue is resolved, are we ready for py 313 release? 

Yes we should be

**Comment by cadenmyers13** [comment]
> > Yes we should be
> 
> 
> 
> @cadenmyers13 I think you are in charge so "yes we should be" is not a helpful/acceptable answer.  "Yes we are" or "no we are not quite yet" are the only acceptable answers.  You can figure out which to say based on going through the checklists and checking things off.

Got it. 

Yes we are ready for release after we fix this.
