### ISSUE TITLE
Ready for 0.2.0 PyPI/GitHub release

### ISSUE THREAD

**Issue by cadenmyers13** [diffpy/diffpy.fourigui#65]
### PyPI/GitHub rc-release checklist:

- [x] All PRs/issues attached to the release are merged.
- [x] All the badges on the README are passing.
- [x] License information is verified as correct. If you are unsure, please comment below.
- [x] Locally rendered documentation contains all appropriate pages, including API references (check no modules are
  missing), tutorials, and other human written text is up-to-date with any changes in the code.
- [x] Installation instructions in the README, documentation and on the website (e.g., diffpy.org) are updated. 
- [x] Successfully run any tutorial examples or do functional testing with the latest Python version.
- [x] Grammar and writing quality are checked (no typos).

Please mention @sbillinge here when you are ready for PyPI/GitHub release. Include any additional comments necessary, such as version information and details about the pre-release here:

### PyPI/GitHub  full-release checklist:
- [x] Create a new conda environment and install the rc from pypi (`pip install <package-name>=??`)
- [x] License information at Pypi is verified as correct. 
- [x] Docs deployed successfully to `diffpy.github.io/<package-name>`
- [x] Successfully run all tests, tutorial examples or do functional testing

Please let  @sbillinge know that all checks are done and package is ready for full release.

### conda-forge release checklist:

- [x] Ensure that the full release has appeared on Pypi successfully
- [x] New package dependencies listed in `conda.txt` and `test.txt` are added to `meta.yaml` in the feedstock.
- [x] Close any open issues on the feedstock.  Reach out to @bobleesj if you have questions
- [x] let @sbillinge and @bobleesj when this is ready

### Post-release checklist

- [x]  Run tutorial examples and conduct functional testing using the installation guide in the README. Attach screenshots/results as comments.
- [x]  Documentation (README, tutorials, API references, and websites) is deployed without broken links or missing figures.

**Comment by cadenmyers13** [comment]
@sbillinge tests passed locally/CI without warnings after installation in a new conda environment, This is ready for `0.2.0rc0` release now

<img width="920" alt="Screenshot 2024-11-11 at 11 22 00 AM" src="https://github.com/user-attachments/assets/7ad0e5bd-9171-47a2-9899-6feb67878232">

![Screenshot 2024-11-11 at 11 22 37 AM](https://github.com/user-attachments/assets/c1964b84-3460-48cd-b67e-e8720356e92f)

**Comment by sbillinge** [comment]
@bobleesj this failed to build because of some error in the README.rst.   I vaguely remember we ran into this before, but don't remember the fix....do you?

**Comment by bobleesj** [comment]
Ok will investigate

**Comment by sbillinge** [comment]
OK, getting rid of the bullet took care of it.  I successfully did an rc release, but the one that worked is `0.2.0rc3`.  @cadenmyers13 please could you test that version from pypi and let me know if it works and I can do a full release.

**Comment by cadenmyers13** [comment]
> OK, getting rid of the bullet took care of it.  I successfully did an rc release, but the one that worked is `0.2.0rc3`.  @cadenmyers13 please could you test that version from pypi and let me know if it works and I can do a full release.

Yep. On it

**Comment by cadenmyers13** [comment]
@sbillinge We have not set up a documentation page (https://github.com/diffpy/diffpy.fourigui/deployments does not exist). Can you configure this in the repo?

**Comment by sbillinge** [comment]
@cadenmyers13 done, docs now appearing.

**Comment by cadenmyers13** [comment]
@sbillinge Alright, checklist is complete. If you want to verify the licensing here's the link: https://pypi.org/project/diffpy.fourigui/0.2.0rc3/

cc: @bobleesj

**Comment by bobleesj** [comment]
@cadenmyers13 I am here for your conda-forge experience. Lmk anytime!

**Comment by cadenmyers13** [comment]
@sbillinge @bobleesj Okay I made a PR in the feedstock updating `meta.yaml` https://github.com/conda-forge/diffpy.fourigui-feedstock/pull/2

**Comment by sbillinge** [comment]
@cadenmyers13 please can you check the docs on this?  I noticed that the API docs didn't seem to build correctly (even though you signed off on this for a full release.....).  Please click all the links and make sure they make sense, and that the API docs would be readable and understandable to someone trying to use the code as a package (API docs target audience is mostly developers or developer-materials scientists not materials scientists )

**Comment by cadenmyers13** [comment]
@sbillinge Maybe I'm missing something here. This is what the API looks like when I build locally. I clicked through the documentation and compared to [diffpy.utils](https://www.diffpy.org/diffpy.utils/index.html) and it generally took the same structure. However, the main difference in the APIs is fourigui doesn't have very detailed docstrings (except the `applycutoff()` method). I can add this if this is what you're looking for. 

![Screenshot 2024-11-12 at 9 35 44 AM](https://github.com/user-attachments/assets/0c5fb0ea-c330-4d82-b3bb-7229e5cea969)

**Comment by bobleesj** [comment]
@cadenmyers13 Please see https://www.diffpy.org/diffpy.fourigui. After (pre)release, we want to test what was released publicly instead of what it's available locally. In the URL, it appears docs and tutorials are not being rendered. I will share anything that I find. It could be due to the CI problem.

**Comment by bobleesj** [comment]
https://www.diffpy.org/diffpy.fourigui/api/diffpy.fourigui.html @cadenmyers13 @sbillinge deployed!

**Comment by sbillinge** [comment]
Great job everyone! 0.2.0 lives!

The conda badge is not showing 0.2.0....does it stlil need to be pushed out to conda-forge?

**Comment by bobleesj** [comment]
https://github.com/conda-forge/diffpy.fourigui-feedstock/blob/main/recipe/conda_build_config.yaml

@sbillinge  it appears that we have `rc` version released, hence we aren't seeing the conda-forge badge. @cadenmyers13 could you please refer to the group's gitlab doc on how to release `rc` via conda. we just need to delete the file that was created to make `rc` in a new PR.

**Comment by cadenmyers13** [comment]
@sbillinge @bobleesj diffpy.fourigui 0.2.0 is live on [conda-forge](https://anaconda.org/conda-forge/diffpy.fourigui)! Links work. I ran some functional testing and things ran smoothly. I'll close this issue if everyone is satisfied 😃 
![Screenshot 2024-12-13 at 12 19 27 PM](https://github.com/user-attachments/assets/6f50fc61-1dbf-48d8-a729-1b557c432992)
![Screenshot 2024-12-13 at 12 19 46 PM](https://github.com/user-attachments/assets/4539edc3-6884-4140-9d4c-dc5e768c2a22)

**Comment by bobleesj** [comment]
Congrats @cadenmyers13 finally! Pls check-off the last items in the issue and close it!

**Comment by bobleesj** [comment]
Delivered!

**Comment by cadenmyers13** [comment]
Delivered indeed 🙌
