### ISSUE TITLE
Doc software version indicates 0.0.1 when rendered via workflow dispatch

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.fourigui#69]
### Problem

<img width="604" alt="Screenshot 2024-11-15 at 10 56 33 AM" src="https://github.com/user-attachments/assets/aba9a0b3-1546-43b3-9bed-1969c974ac41">

The version displays 0.0.1 in https://www.diffpy.org/diffpy.fourigui/.

The version is dynamically retrieved from the latest tag. Here, when a single doc rendering workflow is used, it fails to grab the latest tag.

### Proposed solution

Begin investigating.

**Comment by bobleesj** [comment]
Found the problem. When we checkout, we don't want to just checkout the `main` branch but also grab the latest tags as well.

Change from

```
        uses: actions/checkout@v4
```

to

```
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags
```

### Result

Before:

<img width="536" alt="Screenshot 2024-11-15 at 11 09 06 AM" src="https://github.com/user-attachments/assets/72522400-05e1-44f6-91bc-89d805c6a355">

After:

<img width="526" alt="Screenshot 2024-11-15 at 11 24 59 AM" src="https://github.com/user-attachments/assets/984644d1-974e-40d3-874e-2776fa375aa4">

**Comment by sbillinge** [comment]
fixed!  Nicely done:
![image](https://github.com/user-attachments/assets/f007bb64-d869-4a6c-9d55-a3e914801ede)

closing
