### ISSUE TITLE
API Doc not rendering for diffpy.fourigui

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.fourigui#70]
### Problem

<img width="874" alt="Screenshot 2024-11-15 at 2 36 59 PM" src="https://github.com/user-attachments/assets/4bc6bcbc-cfa0-43bd-b7e5-051c975a8563">

API docs not being rendered after CI deployment: https://www.diffpy.org/diffpy.fourigui/api/diffpy.fourigui.html

### Proposed solution

I've tested that our CI is able to dynamically render API docs: https://bobleesj-test-org.github.io/bobleesj.release/api/diffpy.labpdfproc.html (using labpdfproc as a test case)

@Sparks29032 @cadenmyers13 could you please investigate why fourigui API docs aren't being rendered when hosted?

**Comment by sbillinge** [comment]
Fixed the problem with it not deploying the right version (#69 ), but sadly this didn't fix this issue.  The current online version of the docs still show:
![image](https://github.com/user-attachments/assets/cc959561-3862-46f3-a2c6-bdfdc834adcb)
